Repository hoverinc/ray-tracing-renderer, pull requests merged in 2019-11, with the labels that each got.

#37 chore(sample-models): add scene with sample models
  package-lock.json
  package.json
  scenes/envmaps/gray-background-with-dirlight.hdr
  scenes/sample-models/index.html
  scenes/sample-models/main.js
Labels: refactor

#42 chore(sample-models): create remote example
  README.md
  scenes/sample-models/dev.html
  scenes/sample-models/index.html
  scenes/sample-models/main.js
Labels: enhancement

#43 fix(sample-models): update remote URLs
  README.md
  scenes/sample-models/index.html
Labels: bug

#44 chore(sample-models): menu to switch env map
  scenes/envmaps/blurry-sunset-with-dirlight.hdr
  scenes/sample-models/main.js
Labels: enhancement

#46 Improved sample-models mobile support
  scenes/sample-models/index.html
Labels: enhancement
