Repository hoverinc/ray-tracing-renderer, pull requests merged in 2019-10, with the labels that each got.

#23 chore(package-name): update npm package name
  package.json
Labels: documentation

#24 chore(package.json): update package.json
  package-lock.json
  package.json
Labels: refactor

#19 Multiple render targets; Refactors
  src/RayTracingRenderer.js
  src/renderer/Framebuffer.js
  src/renderer/FullscreenQuad.js
  src/renderer/RayTracingShader.js
  src/renderer/RenderTargets.js
  src/renderer/RenderingPipeline.js
  src/renderer/StratifiedSampler.js
  src/renderer/StratifiedSamplerCombined.js
  src/renderer/Texture.js
  src/renderer/TextureAllocator.js
  src/renderer/TileRender.js
  src/renderer/ToneMapShader.js
  src/renderer/addGeometryIndices.js
  src/renderer/glsl/chunks/bsdf.glsl
  src/renderer/glsl/chunks/envmap.glsl
  src/renderer/glsl/chunks/intersect.glsl
  src/renderer/glsl/chunks/random.glsl
  src/renderer/glsl/chunks/sample.glsl
  src/renderer/glsl/chunks/sampleGlassMicrofacet.glsl
  src/renderer/glsl/chunks/sampleGlassSpecular.glsl
  src/renderer/glsl/chunks/sampleMaterial.glsl
  src/renderer/glsl/chunks/sampleShadowCatcher.glsl
  src/renderer/glsl/chunks/textureLinear.glsl
  src/renderer/glsl/fullscreenQuad.vert
  src/renderer/glsl/rayTrace.frag
  src/renderer/glsl/toneMap.frag
  src/renderer/mergeMeshesToGeometry.js
  src/renderer/renderTarget.js
Labels: refactor

#17 Optimize Envmap Creation
  src/renderer/envMapCreation.js
  src/renderer/rgbeToFloat.js
  test/envMapCreation.test.js
Labels: enhancement

#27 Tweak Directional Light
  src/SoftDirectionalLight.js
  src/renderer/envMapCreation.js
  src/renderer/rgbeToFloat.js
Labels: refactor

#29 Fix module importing
  src/main.js
  src/renderer/RayTracingShader.js
Labels: bug

#31 chore(npmjs): publish npm package automatically
  .github/workflows/publish_package.yml
Labels: enhancement

#32 chore(instanceof): remove instanceof usage
  src/EnvironmentLight.js
  src/renderer/RayTracingShader.js
  test/EnvironmentLight.test.js
Labels: refactor

#33 chore(build): automate build process
  .gitignore
  .release-it.json
  package-lock.json
  package.json
  scripts/env-vars.sh
  scripts/release.sh
Labels: enhancement

#34 Use ES6 build for the main library entry point
  package.json
Labels: build
