Repository hoverinc/ray-tracing-renderer, pull requests merged in 2019-09, with the labels that each got.

#7 Blue noise
  src/RayTracingRenderer.js
  src/renderer/glsl/chunks/random.glsl
  src/renderer/glsl/chunks/sampleGlassMicrofacet.glsl
  src/renderer/glsl/chunks/sampleGlassSpecular.glsl
  src/renderer/glsl/chunks/sampleMaterial.glsl
  src/renderer/glsl/chunks/sampleShadowCatcher.glsl
  src/renderer/glsl/rayTrace.frag
  src/renderer/rayTracingShader.js
  src/renderer/renderingPipeline.js
  src/renderer/stratifiedRandom.js
  src/renderer/stratifiedRandomCombined.js
  src/renderer/stratifiedSampler.js
  src/renderer/stratifiedSamplerCombined.js
  src/renderer/texture.js
  src/renderer/texture/HDR_L_0.png
  src/renderer/texture/noise.js
  src/renderer/texture/readme.txt
Labels: enhancement

#13 Clean-up before denoising
  src/RayTracingRenderer.js
  src/constants.js
  src/main.js
  src/renderer/addGeometryIndices.js
  src/renderer/bvhAccel.js
  src/renderer/bvhUtil.js
  src/renderer/envMapCreation.js
  src/renderer/envmapDistribution.js
  src/renderer/fullscreenQuad.js
  src/renderer/glUtil.js
  src/renderer/glsl/chunks/envmap.glsl
  src/renderer/glsl/chunks/sampleGlassMicrofacet.glsl
  src/renderer/glsl/chunks/sampleGlassSpecular.glsl
  src/renderer/glsl/chunks/sampleShadowCatcher.glsl
  src/renderer/glsl/rayTrace.frag
  src/renderer/glsl/toneMap.frag
  src/renderer/mergeMeshesToGeometry.js
  src/renderer/rayTracingShader.js
  src/renderer/renderTarget.js
  src/renderer/renderingPipeline.js
  src/renderer/rgbeToFloat.js
  src/renderer/stratifiedSampler.js
  src/renderer/stratifiedSamplerCombined.js
  src/renderer/texture.js
  src/renderer/texture/readme.txt
  src/renderer/textureAllocator.js
  src/renderer/texturesFromMaterials.js
  src/renderer/tileRender.js
  src/renderer/toneMapShader.js
  src/renderer/uploadBuffers.js
Labels: refactor

#16 Expand .gitignore
  .gitignore
Labels: refactor

#18 Create workflow (Github Actions) to run tests automatically
  .github/main.workflow
  .nvmrc
  package-lock.json
  package.json
Labels: enhancement

#21 Convert main.workflow to Actions V2 yml files
  .github/main.workflow
  .github/workflows/push.yml
Labels: refactor

#22 Fix npm install path
  README.md
Labels: documentation
