Repository hoverinc/ray-tracing-renderer, pull requests merged in 2020-01, with the labels that each got.

#57 Pipeline refactor
  src/RayTracingRenderer.js
  src/renderer/Framebuffer.js
  src/renderer/FullscreenQuad.js
  src/renderer/RayTracePass.js
  src/renderer/RenderPass.js
  src/renderer/RenderTargets.js
  src/renderer/RenderingPipeline.js
  src/renderer/ReprojectPass.js
  src/renderer/ReprojectShader.js
  src/renderer/Texture.js
  src/renderer/TextureAllocator.js
  src/renderer/ToneMapPass.js
  src/renderer/ToneMapShader.js
  src/renderer/UniformSetter.js
  src/renderer/glUtil.js
  src/renderer/glsl/chunks/bsdf.glsl
  src/renderer/glsl/chunks/core.glsl
  src/renderer/glsl/chunks/envmap.glsl
  src/renderer/glsl/chunks/intersect.glsl
  src/renderer/glsl/chunks/random.glsl
  src/renderer/glsl/chunks/sample.glsl
  src/renderer/glsl/chunks/sampleGlassMicrofacet.glsl
  src/renderer/glsl/chunks/sampleGlassSpecular.glsl
  src/renderer/glsl/chunks/sampleMaterial.glsl
  src/renderer/glsl/chunks/sampleShadowCatcher.glsl
  src/renderer/glsl/chunks/textureLinear.glsl
  src/renderer/glsl/fullscreenQuad.vert
  src/renderer/glsl/rayTrace.frag
  src/renderer/glsl/reproject.frag
  src/renderer/glsl/toneMap.frag
  src/renderer/glslUtil.js
Labels: refactor

#61 Tile timing fix
  src/renderer/RenderingPipeline.js
  src/renderer/TileRender.js
Labels: bug

#62 Hybrid rendering
  src/RayTracingRenderer.js
  src/renderer/Framebuffer.js
  src/renderer/FullscreenQuad.js
  src/renderer/GBufferPass.js
  src/renderer/MaterialBuffer.js
  src/renderer/RayTracePass.js
  src/renderer/RenderPass.js
  src/renderer/RenderingPipeline.js
  src/renderer/ReprojectPass.js
  src/renderer/Texture.js
  src/renderer/ToneMapPass.js
  src/renderer/UniformBuffer.js
  src/renderer/UniformSetter.js
  src/renderer/bvhAccel.js
  src/renderer/decomposeScene.js
  src/renderer/glUtil.js
  src/renderer/glsl/chunks/constants.glsl
  src/renderer/glsl/chunks/intersect.glsl
  src/renderer/glsl/chunks/materialBuffer.glsl
  src/renderer/glsl/chunks/random.glsl
  src/renderer/glsl/chunks/rayTraceCore.glsl
  src/renderer/glsl/chunks/sampleMaterial.glsl
  src/renderer/glsl/chunks/surfaceInteractionDirect.glsl
  src/renderer/glsl/gBuffer.frag
  src/renderer/glsl/gBuffer.vert
  src/renderer/glsl/rayTrace.frag
  src/renderer/glsl/reproject.frag
  src/renderer/glsl/toneMap.frag
  src/renderer/mergeMeshesToGeometry.js
  src/renderer/uploadBuffers.js
Labels: enhancement

#66 Fix glsl error when scene has no materials with maps
  src/renderer/glsl/chunks/intersect.glsl
Labels: bug
